/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source code lives in the src/ folder of this plugin.
The classifier in src/classifier.ts is ported from the MIT-licensed
Detexify project (https://github.com/kirel/detexify).
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DetexifyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/classifier.ts
var EPSILON = 1e-10;
var ANGLE_THRESHOLD = 2 * Math.PI * 15 / 360;
var UNIT_RECT = [
  { x: 0, y: 0 },
  { x: 1, y: 1 }
];
function point(x, y) {
  return { x, y };
}
function add(a, b) {
  return point(a.x + b.x, a.y + b.y);
}
function sub(a, b) {
  return point(a.x - b.x, a.y - b.y);
}
function scale(s, p) {
  return point(s * p.x, s * p.y);
}
function dot(a, b) {
  return a.x * b.x + a.y * b.y;
}
function norm(p) {
  return Math.sqrt(dot(p, p));
}
function manhattan(a, b) {
  return Math.abs(a.x - b.x) + Math.abs(a.y - b.y);
}
function samePoint(a, b) {
  return a.x === b.x && a.y === b.y;
}
function closePoint(a, b) {
  return norm(sub(a, b)) < EPSILON;
}
function clamp(value, lo, hi) {
  return Math.max(lo, Math.min(hi, value));
}
function strokeLength(stroke) {
  let total = 0;
  for (let i = 1; i < stroke.length; i += 1) {
    total += norm(sub(stroke[i], stroke[i - 1]));
  }
  return total;
}
function boundingBox(stroke) {
  if (stroke.length === 0) {
    throw new Error("An empty stroke has no bounding box");
  }
  let minX = stroke[0].x;
  let minY = stroke[0].y;
  let maxX = minX;
  let maxY = minY;
  for (const p of stroke.slice(1)) {
    minX = Math.min(minX, p.x);
    minY = Math.min(minY, p.y);
    maxX = Math.max(maxX, p.x);
    maxY = Math.max(maxY, p.y);
  }
  return [point(minX, minY), point(maxX, maxY)];
}
function scaleToRect(target, stroke) {
  if (stroke.length === 0) return [];
  const [lo, hi] = target;
  if (lo.x > hi.x || lo.y > hi.y) {
    throw new Error("Invalid target rectangle");
  }
  const [bMin, bMax] = boundingBox(stroke);
  const w = bMax.x - bMin.x;
  const h = bMax.y - bMin.y;
  const tw = hi.x - lo.x;
  const th = hi.y - lo.y;
  const sx = w === 0 ? 1 : 1 / w * tw;
  const sy = h === 0 ? 1 : 1 / h * th;
  const ox = w === 0 ? lo.x + 0.5 * tw : lo.x;
  const oy = h === 0 ? lo.y + 0.5 * th : lo.y;
  return stroke.map((p) => point((p.x - bMin.x) * sx + ox, (p.y - bMin.y) * sy + oy));
}
function fitRect(bbox, target) {
  const [bMin, bMax] = bbox;
  const [tMin, tMax] = target;
  if (samePoint(bMin, bMax)) {
    const center = scale(0.5, add(tMin, tMax));
    return [center, center];
  }
  const bw = bMax.x - bMin.x;
  const bh = bMax.y - bMin.y;
  const tw = tMax.x - tMin.x;
  const th = tMax.y - tMin.y;
  const bAspect = bw / bh;
  const tAspect = tw / th;
  const wider = bAspect > tAspect;
  const factor = wider ? tw / bw : th / bh;
  const offset = wider ? point(0, (th - factor * bh) / 2) : point((tw - factor * bw) / 2, 0);
  const mapPoint = (p) => add(add(scale(factor, sub(p, bMin)), offset), tMin);
  return [mapPoint(bMin), mapPoint(bMax)];
}
function fitToUnitSquare(stroke) {
  if (stroke.length === 0) return [];
  return scaleToRect(fitRect(boundingBox(stroke), UNIT_RECT), stroke);
}
function dedupe(stroke) {
  if (stroke.length < 2) return [...stroke];
  const out = [stroke[0]];
  for (const p of stroke.slice(1)) {
    if (!closePoint(p, out[out.length - 1])) out.push(p);
  }
  return out;
}
function smooth(stroke) {
  if (stroke.length < 3) return [...stroke];
  const out = [stroke[0]];
  for (let i = 0; i + 2 < stroke.length; i += 1) {
    out.push(scale(1 / 3, add(add(stroke[i], stroke[i + 1]), stroke[i + 2])));
  }
  out.push(...stroke.slice(-1));
  return out;
}
function redistributeByDistance(distance, stroke) {
  if (distance <= 0) throw new Error("Cannot redistribute with non-positive distance");
  if (stroke.length < 2) return [...stroke];
  const out = [stroke[0]];
  let budget = distance;
  let anchor = stroke[0];
  let rest = stroke.slice(1);
  let next = rest[0];
  while (rest.length > 0) {
    const diff = sub(next, anchor);
    const len = norm(diff);
    if (len < budget) {
      anchor = next;
      rest = rest.slice(1);
      if (rest.length > 0) next = rest[0];
      budget -= len;
    } else {
      const created = add(anchor, scale(budget / len, diff));
      out.push(created);
      anchor = created;
      budget = distance;
    }
  }
  const last = stroke[stroke.length - 1];
  if (last && out[out.length - 1] !== last && !samePoint(out[out.length - 1], last)) {
    out.push(last);
  }
  return out;
}
function redistributeToCount(count, stroke) {
  if (stroke.length === 0) return [];
  if (stroke.length === 1) return [...stroke];
  return redistributeByDistance(strokeLength(stroke) / (count - 1), stroke);
}
function cornerAngle(prev, mid, next) {
  const a = sub(mid, prev);
  const b = sub(next, mid);
  const denom = norm(a) * norm(b);
  if (denom === 0) return 0;
  return Math.acos(clamp(dot(a, b) / denom, -1, 1));
}
function dropFlatPoints(threshold, stroke) {
  if (stroke.length < 3) return [...stroke];
  const out = [stroke[0]];
  let prev = stroke[0];
  let mid = stroke[1];
  for (let i = 2; i < stroke.length; i += 1) {
    const next = stroke[i];
    if (cornerAngle(prev, mid, next) >= threshold) {
      out.push(mid);
      prev = mid;
    }
    mid = next;
  }
  out.push(mid);
  return out;
}
function preprocess(strokes) {
  return strokes.slice(0, 10).map(
    (stroke) => dropFlatPoints(
      ANGLE_THRESHOLD,
      dedupe(redistributeToCount(10, fitToUnitSquare(smooth(dedupe(stroke)))))
    )
  );
}
function flatten(strokes) {
  const out = [];
  for (const stroke of strokes) out.push(...stroke);
  return out;
}
function dtw(a, b) {
  if (a.length === 0 && b.length === 0) {
    throw new Error("Cannot compare two empty series");
  }
  if (a.length === 0) return dtw(b, a);
  if (b.length === 0) throw new Error("Cannot compare empty series");
  let s = a;
  let r = b;
  let si = 0;
  let ri = 0;
  let acc = manhattan(s[si], r[ri]);
  let steps = 1;
  while (s.length - si > 1 && r.length - ri > 1) {
    const moveS = manhattan(s[si + 1], r[ri]);
    const moveBoth = manhattan(s[si + 1], r[ri + 1]);
    const moveR = manhattan(s[si], r[ri + 1]);
    const best = Math.min(moveS, moveBoth, moveR);
    if (moveS === best) {
      si += 1;
      acc += moveS;
    } else if (moveBoth === best) {
      si += 1;
      ri += 1;
      acc += moveBoth;
    } else {
      ri += 1;
      acc += moveR;
    }
    steps += 1;
  }
  if (r.length - ri === 1) {
    const ts = s;
    const tsi = si;
    s = r;
    si = ri;
    r = ts;
    ri = tsi;
  }
  if (s.length - si !== 1) throw new Error("Unexpected DTW state");
  for (let i = ri + 1; i < r.length; i += 1) {
    acc += manhattan(s[si], r[i]);
    steps += 1;
  }
  return acc / steps;
}
function mean(values) {
  if (values.length === 0) return Number.POSITIVE_INFINITY;
  return values.reduce((sum, v) => sum + v, 0) / values.length;
}
function validStrokes(strokes) {
  return strokes.length > 0 && strokes.every((s) => s.length > 0);
}
var DetexifyClassifier = class {
  constructor(snapshot, meanNearest = 2) {
    if (meanNearest <= 0) throw new Error("meanNearest must be positive");
    this.meanNearest = meanNearest;
    this.preparedSymbols = Object.entries(snapshot).map(([id, samples]) => ({
      id,
      samples: samples.map((sample) => flatten(sample.strokes))
    }));
  }
  classify(strokes, limit = 10) {
    if (!validStrokes(strokes)) return [];
    const query = flatten(preprocess(strokes));
    const hits = [];
    for (const symbol of this.preparedSymbols) {
      if (symbol.samples.length === 0) continue;
      const distances = symbol.samples.map((sample) => dtw(query, sample)).sort((x, y) => x - y);
      hits.push({ id: symbol.id, score: mean(distances.slice(0, this.meanNearest)) });
    }
    hits.sort((x, y) => x.score - y.score);
    return limit === void 0 ? hits : hits.slice(0, limit);
  }
};

// src/data.ts
var import_obsidian = require("obsidian");
function backslashToUnderscore(id) {
  return id.replace(/\\/g, "_");
}
function indexSymbols(symbols) {
  const map = /* @__PURE__ */ new Map();
  for (const symbol of symbols) {
    if (typeof symbol.legacyId === "string") {
      map.set(symbol.legacyId, symbol);
      map.set(backslashToUnderscore(symbol.legacyId), symbol);
    }
    if (typeof symbol.id === "string") map.set(symbol.id, symbol);
  }
  return map;
}
var DataStore = class {
  constructor(app, pluginDir) {
    this.app = app;
    this.symbolsPath = (0, import_obsidian.normalizePath)(`${pluginDir}/data/symbols.json`);
    this.snapshotPath = (0, import_obsidian.normalizePath)(`${pluginDir}/data/snapshot.json`);
  }
  async load() {
    const adapter = this.app.vault.adapter;
    const [symbolsRaw, snapshotRaw] = await Promise.all([
      adapter.read(this.symbolsPath),
      adapter.read(this.snapshotPath)
    ]);
    const symbols = JSON.parse(symbolsRaw);
    const snapshot = JSON.parse(snapshotRaw);
    return { symbols, snapshot, symbolsById: indexSymbols(symbols) };
  }
};

// src/mathContext.ts
function isInsideMath(text, offset) {
  let state = "text";
  let contentStart = 0;
  let i = 0;
  const within = (start, end) => offset >= start && offset <= end;
  while (i < text.length) {
    const char = text[i];
    if (char === "\\") {
      i += 2;
      continue;
    }
    if (char !== "$") {
      i += 1;
      continue;
    }
    const isDouble = text[i + 1] === "$";
    if (state === "text") {
      if (isDouble) {
        state = "display";
        contentStart = i + 2;
        i += 2;
      } else {
        state = "inline";
        contentStart = i + 1;
        i += 1;
      }
      continue;
    }
    if (state === "display") {
      if (isDouble) {
        if (within(contentStart, i)) return true;
        state = "text";
        i += 2;
      } else {
        i += 1;
      }
      continue;
    }
    if (within(contentStart, i)) return true;
    state = "text";
    i += 1;
  }
  if (state !== "text" && offset >= contentStart) return true;
  return false;
}

// src/main.ts
var VIEW_TYPE = "detexify-panel-view";
var DEFAULT_STATUS = "Draw a symbol or search above.";
var DEFAULT_SETTINGS = {
  resultLimit: 12
};
function toResult(meta) {
  return { command: meta.command, packageName: meta.package };
}
var DetexifyPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.classifier = null;
    this.data = null;
    this.lastActiveMarkdownView = null;
    this.loadPromise = null;
  }
  async onload() {
    var _a;
    await this.loadSettings();
    this.dataStore = new DataStore(this.app, (_a = this.manifest.dir) != null ? _a : "");
    this.registerView(VIEW_TYPE, (leaf) => new DetexifyView(leaf, this));
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if ((leaf == null ? void 0 : leaf.view) instanceof import_obsidian2.MarkdownView) {
          this.lastActiveMarkdownView = leaf.view;
        }
      })
    );
    const active = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
    if (active) this.lastActiveMarkdownView = active;
    this.addRibbonIcon("sigma", "Open LaTeX symbol picker", () => this.activateView());
    this.addCommand({
      id: "open-panel",
      name: "Open panel",
      callback: () => this.activateView()
    });
    this.addSettingTab(new DetexifySettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    const stored = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, stored != null ? stored : {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const existing = workspace.getLeavesOfType(VIEW_TYPE);
    if (existing.length > 0) {
      leaf = existing[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) await leaf.setViewState({ type: VIEW_TYPE, active: true });
    }
    if (leaf) await workspace.revealLeaf(leaf);
  }
  ensureClassifier() {
    if (this.classifier) return Promise.resolve();
    if (!this.loadPromise) {
      this.loadPromise = this.dataStore.load().then((data) => {
        this.data = data;
        this.classifier = new DetexifyClassifier(data.snapshot);
      }).catch((error) => {
        this.loadPromise = null;
        throw error;
      });
    }
    return this.loadPromise;
  }
  classify(strokes) {
    if (!this.classifier || !this.data) return [];
    return this.classifier.classify(strokes, this.settings.resultLimit).map((hit) => {
      var _a;
      return (_a = this.data) == null ? void 0 : _a.symbolsById.get(hit.id);
    }).filter((meta) => meta !== void 0).map(toResult);
  }
  search(query, limit = 80) {
    var _a, _b;
    const needle = query.toLowerCase();
    const seen = /* @__PURE__ */ new Set();
    const results = [];
    for (const meta of (_b = (_a = this.data) == null ? void 0 : _a.symbols) != null ? _b : []) {
      if (seen.has(meta.command)) continue;
      if (!`${meta.command} ${meta.package}`.toLowerCase().includes(needle)) continue;
      seen.add(meta.command);
      results.push(toResult(meta));
      if (results.length >= limit) break;
    }
    return results;
  }
  insertSymbol(command) {
    var _a;
    const view = (_a = this.lastActiveMarkdownView) != null ? _a : this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
    if (!view) {
      new import_obsidian2.Notice("Open a note before inserting a symbol.");
      return;
    }
    const editor = view.editor;
    if (!editor.hasFocus()) editor.focus();
    const offset = editor.posToOffset(editor.getCursor());
    const inside = isInsideMath(editor.getValue(), offset);
    let text = command;
    let caret = command.length;
    const braceIndex = command.indexOf("{}");
    if (braceIndex >= 0) caret = braceIndex + 1;
    if (!inside) {
      text = `$${command}$`;
      caret += 1;
    }
    editor.replaceSelection(text);
    const start = editor.posToOffset(editor.getCursor()) - text.length;
    editor.setCursor(editor.offsetToPos(start + caret));
    editor.focus();
  }
};
var DetexifyView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.dpr = 1;
    this.strokes = [];
    this.drawing = false;
    this.activePointer = null;
    this.resizeObserver = null;
    this.renderToken = 0;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "LaTeX symbol picker";
  }
  getIcon() {
    return "sigma";
  }
  async onOpen() {
    const root = this.contentEl;
    root.empty();
    root.addClass("detexify-panel");
    const searchRow = root.createDiv({ cls: "detexify-search-row" });
    this.searchEl = searchRow.createEl("input", {
      type: "text",
      cls: "detexify-search-input",
      attr: { placeholder: "Search command, e.g. \\alpha, int, mathbb\u2026" }
    });
    this.registerDomEvent(this.searchEl, "input", () => this.onSearch());
    const clearBtn = searchRow.createEl("button", { cls: "detexify-clear-btn", text: "Clear" });
    this.registerDomEvent(clearBtn, "click", () => this.clearAll());
    const canvasWrap = root.createDiv({ cls: "detexify-canvas-wrap" });
    this.canvas = canvasWrap.createEl("canvas", { cls: "detexify-canvas" });
    const ctx = this.canvas.getContext("2d");
    if (!ctx) throw new Error("Detexify: could not get 2D canvas context");
    this.ctx = ctx;
    this.setupCanvasEvents();
    this.statusEl = root.createDiv({ cls: "detexify-status" });
    this.resultsEl = root.createDiv({ cls: "detexify-results" });
    this.registerDomEvent(this.resultsEl, "mousedown", (event) => {
      const target = event.target;
      const button = target == null ? void 0 : target.closest(".detexify-result");
      if (!button) return;
      event.preventDefault();
      event.stopPropagation();
      const command = button.dataset.command;
      if (command) this.plugin.insertSymbol(command);
    });
    this.resizeObserver = new ResizeObserver(() => this.resizeCanvas());
    this.resizeObserver.observe(canvasWrap);
    this.resizeCanvas();
    this.setStatus("Loading\u2026");
    try {
      await this.plugin.ensureClassifier();
      this.setStatus(DEFAULT_STATUS);
    } catch (error) {
      console.error(error);
      this.setStatus("Failed to load classifier data. Try reinstalling the plugin.");
    }
  }
  async onClose() {
    var _a;
    (_a = this.resizeObserver) == null ? void 0 : _a.disconnect();
    this.resizeObserver = null;
  }
  setStatus(message) {
    this.statusEl.setText(message);
  }
  resizeCanvas() {
    const wrap = this.canvas.parentElement;
    if (!wrap) return;
    const width = wrap.clientWidth;
    const height = this.canvas.clientHeight || 190;
    this.dpr = window.devicePixelRatio || 1;
    this.canvas.width = Math.max(1, Math.floor(width * this.dpr));
    this.canvas.height = Math.max(1, Math.floor(height * this.dpr));
    this.ctx.setTransform(this.dpr, 0, 0, this.dpr, 0, 0);
    this.redraw();
  }
  setupCanvasEvents() {
    const pointFromEvent = (event) => {
      const rect = this.canvas.getBoundingClientRect();
      return { x: event.clientX - rect.left, y: event.clientY - rect.top };
    };
    this.registerDomEvent(this.canvas, "pointerdown", (event) => {
      if (this.activePointer !== null) return;
      event.preventDefault();
      this.activePointer = event.pointerId;
      this.canvas.setPointerCapture(event.pointerId);
      this.drawing = true;
      this.strokes.push([pointFromEvent(event)]);
      this.redraw();
    });
    this.registerDomEvent(this.canvas, "pointermove", (event) => {
      if (!this.drawing || event.pointerId !== this.activePointer) return;
      event.preventDefault();
      const stroke = this.strokes[this.strokes.length - 1];
      stroke.push(pointFromEvent(event));
      this.redraw();
    });
    const finishStroke = (event) => {
      if (event.pointerId !== this.activePointer) return;
      this.drawing = false;
      this.activePointer = null;
      this.classify();
    };
    this.registerDomEvent(this.canvas, "pointerup", finishStroke);
    this.registerDomEvent(this.canvas, "pointercancel", finishStroke);
  }
  redraw() {
    const ctx = this.ctx;
    const cssWidth = this.canvas.width / this.dpr;
    const cssHeight = this.canvas.height / this.dpr;
    ctx.clearRect(0, 0, cssWidth, cssHeight);
    const style = getComputedStyle(this.canvas);
    this.drawGrid(cssWidth, cssHeight, style);
    ctx.strokeStyle = style.getPropertyValue("--detexify-ink") || "#cdd6f4";
    ctx.lineWidth = 3;
    ctx.lineJoin = "round";
    ctx.lineCap = "round";
    for (const stroke of this.strokes) {
      if (stroke.length === 0) continue;
      ctx.beginPath();
      ctx.moveTo(stroke[0].x, stroke[0].y);
      if (stroke.length === 1) {
        ctx.lineTo(stroke[0].x + 0.01, stroke[0].y);
      } else {
        for (const point2 of stroke.slice(1)) ctx.lineTo(point2.x, point2.y);
      }
      ctx.stroke();
    }
  }
  /** Draw a subtle dot grid at the intersections, like a Logseq whiteboard. */
  drawGrid(width, height, style) {
    const ctx = this.ctx;
    const spacing = 22;
    const radius = 1;
    const match = style.color.match(/\d+(\.\d+)?/g);
    const rgb = match ? `${match[0]}, ${match[1]}, ${match[2]}` : "128, 128, 128";
    ctx.save();
    ctx.fillStyle = `rgba(${rgb}, 0.22)`;
    for (let x = spacing; x < width; x += spacing) {
      for (let y = spacing; y < height; y += spacing) {
        ctx.beginPath();
        ctx.arc(x, y, radius, 0, 2 * Math.PI);
        ctx.fill();
      }
    }
    ctx.restore();
  }
  /** Reset the canvas, the search box, the results and the status line. */
  clearAll() {
    this.strokes = [];
    this.searchEl.value = "";
    this.redraw();
    this.resultsEl.empty();
    this.setStatus(DEFAULT_STATUS);
  }
  classify() {
    if (this.searchEl.value.trim()) return;
    if (!this.plugin.classifier) {
      this.setStatus("Still loading\u2026");
      return;
    }
    if (this.strokes.length === 0) return;
    this.setStatus("Matching\u2026");
    const results = this.plugin.classify(this.strokes);
    void this.renderResults(
      results,
      (count) => this.setStatus(count > 0 ? "Click a result to insert it." : "No match, try drawing again.")
    );
  }
  onSearch() {
    const query = this.searchEl.value.trim();
    if (!query) {
      this.resultsEl.empty();
      this.classify();
      return;
    }
    if (!this.plugin.classifier) {
      this.setStatus("Still loading\u2026");
      return;
    }
    const results = this.plugin.search(query);
    void this.renderResults(
      results,
      (count) => this.setStatus(
        count > 0 ? `${count} symbol${count === 1 ? "" : "s"}. Click to insert.` : "No matching symbol."
      )
    );
  }
  async renderResults(results, onDone) {
    const token = ++this.renderToken;
    this.resultsEl.empty();
    onDone(results.length);
    if (results.length === 0) return;
    const grid = this.resultsEl.createDiv({ cls: "detexify-grid" });
    for (const result of results) this.buildTile(grid, result);
    await (0, import_obsidian2.finishRenderMath)();
    if (token !== this.renderToken) return;
  }
  buildTile(grid, result) {
    const button = grid.createEl("button", { cls: "detexify-result" });
    button.dataset.command = result.command;
    button.setAttr("aria-label", `${result.command} (${result.packageName})`);
    const preview = button.createDiv({ cls: "detexify-result-preview" });
    button.createDiv({ cls: "detexify-result-code", text: result.command });
    try {
      preview.appendChild((0, import_obsidian2.renderMath)(result.command, false));
    } catch (error) {
      console.warn("Failed to render", result.command, error);
    }
  }
};
var DetexifySettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Number of draw results").setDesc("How many matches to show after drawing a symbol.").addSlider(
      (slider) => slider.setLimits(4, 24, 1).setValue(this.plugin.settings.resultLimit).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.resultLimit = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
