import symbolsData from "../data/symbols.json";
import snapshotData from "../data/snapshot.json";
import synonymsData from "../synonyms.json";
import type { Snapshot, SymbolMeta } from "./classifier";

/**
 * Bundled snapshot is stored compactly to keep main.js small: each point is a
 * `[x, y]` pair and each sample is just its array of strokes. We inflate it to
 * the classifier's `{ strokes: { x, y }[][] }` shape once at load time.
 */
type CompactSnapshot = Record<string, number[][][][]>;

export interface ClassifierData {
	snapshot: Snapshot;
	symbols: SymbolMeta[];
	symbolsById: Map<string, SymbolMeta>;
	synonymsByCommand: Map<string, string[]>;
}

function backslashToUnderscore(id: string): string {
	return id.replace(/\\/g, "_");
}

function indexSymbols(symbols: SymbolMeta[]): Map<string, SymbolMeta> {
	const map = new Map<string, SymbolMeta>();
	for (const symbol of symbols) {
		if (typeof symbol.legacyId === "string") {
			map.set(symbol.legacyId, symbol);
			map.set(backslashToUnderscore(symbol.legacyId), symbol);
		}
		if (typeof symbol.id === "string") map.set(symbol.id, symbol);
	}
	return map;
}

/**
 * The classifier data is generated by scripts/build-data.cjs and inlined into
 * main.js at build time, so the plugin works fully offline with nothing extra
 * to ship alongside the bundle.
 */
function indexSynonyms(): Map<string, string[]> {
	const raw = synonymsData as Record<string, string[]>;
	const map = new Map<string, string[]>();
	for (const [command, keywords] of Object.entries(raw)) {
		map.set(command, keywords.map((keyword) => keyword.toLowerCase()));
	}
	return map;
}

function inflateSnapshot(raw: CompactSnapshot): Snapshot {
	const snapshot: Snapshot = {};
	for (const id of Object.keys(raw)) {
		snapshot[id] = raw[id].map((strokes) => ({
			strokes: strokes.map((stroke) => stroke.map(([x, y]) => ({ x, y }))),
		}));
	}
	return snapshot;
}

export function loadClassifierData(): ClassifierData {
	const symbols = symbolsData as SymbolMeta[];
	const snapshot = inflateSnapshot(snapshotData as CompactSnapshot);
	return {
		symbols,
		snapshot,
		symbolsById: indexSymbols(symbols),
		synonymsByCommand: indexSynonyms(),
	};
}
